"""empty message

Revision ID: 498c0554bf32
Revises: 67c1c21a842c
Create Date: 2022-02-11 15:46:07.272074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c0554bf32'
down_revision = '67c1c21a842c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
