"""empty message

Revision ID: 86bfcc615bbf
Revises: 77937f6f3896
Create Date: 2022-02-12 23:14:12.068985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bfcc615bbf'
down_revision = '77937f6f3896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('post', 'blog',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'blog',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
