"""empty message

Revision ID: f05459d20a78
Revises: 82f8b195f071
Create Date: 2022-02-12 22:29:12.556059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05459d20a78'
down_revision = '82f8b195f071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_constraint('blog_name_key', 'blog', type_='unique')
    op.create_unique_constraint(None, 'blog', ['title'])
    op.drop_column('blog', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog', type_='unique')
    op.create_unique_constraint('blog_name_key', 'blog', ['name'])
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
