name: AWS OIDC Example
env:
  AWS_REGION: "eu-west-1"
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:

  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::656670204193:role/github.com
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          docker build -t flask-github .
          docker tag flask-github:latest 656670204193.dkr.ecr.eu-west-1.amazonaws.com/flask-github:latest
          docker push 656670204193.dkr.ecr.eu-west-1.amazonaws.com/flask-github:latest
